server:
  port: 10010
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
zuul:
  prefix: /api # 添加路由前缀
  routes:
    item-service: /item/**
    search-service: /search/**
    user-service: /user/**
    auth-service: /auth/**
    upload-service:
      path: /upload/**
      serviceId: upload-service
      strip-prefix: false
  add-host-header: true
  sensitive-headers:

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000 # 熔断超时时长 ms
ribbon:
  ConnectTimeout: 1000  # ribbon 链接超时时长
  ReadTimeout: 3500   # ribbon 读取超时时长
  MaxAutoRetries: 0   # 当前服务重试次数
  MaxAutoRetriesNextServer: 0   #切换服务重试次数

ly:
  jwt:
    pubKeyPath: "C:\\tmp\\rsa\\rsa.pub" # 公钥地址
    cookieName: LY_TOKEN
  filter:
    allowPaths:
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item